### ISSUE TITLE
Smoke launchers

### ISSUE THREAD

**Issue by D4nte64** [Toonu/Tripartite#1]
Please add the option to change the camouflage of the BDAc smoke launchers and make them a bit smaller (about 60-75% of their current size).

**Comment by Toonu** [comment]
From your words, I know the targeting ball and ERA for camouflage. Will do.

**Comment by Toonu** [comment]
25c215ce91ac9c48d5ee84a6103ee7cc12c20b52

**Comment by Toonu** [comment]
Fixed and added in latest patch. Closing.
